version: '2'

services:
  postgres:
    restart: on-failure:10
    image: postgres:9.6
    container_name: pg_auginc
    volumes:
      - "auginc_postgres:/pgdata"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/pgdata

volumes:
  auginc_postgres:
