spring:
    jpa:
        hibernate:
            naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
            use-new-id-generator-mappings: true
    datasource:
        initialize: false
    profiles:
        active: in-memory-db,development
    data:
        rest:
            base-path: /api
logging:
    config: classpath:logback-console.xml

---
spring:
    profiles: production
logging:
    config: classpath:logback-file.xml

---
spring:
    profiles: development
    datasource:
        initialize: true

---
spring:
    profiles: real-db
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: validate
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/auginc
        username: postgres
        password: postgres
flyway:
    schemas: public

---
spring:
    profiles: in-memory-db
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:auginc;DB_CLOSE_DELAY\=-1
        username: sa
        password:
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.H2Dialect
            ddl-auto: create
flyway:
    enabled: false
