spring:
    jpa:
        hibernate:
            naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
            use-new-id-generator-mappings: true
    profiles:
        active: real-db,development,granular-security
    jackson:
        serialization:
            INDENT_OUTPUT: true
        mapper:
            infer-property-mutators: false
logging:
    config: classpath:logback-console.xml
security:
    basic:
        enabled: false
auginc:
    jwt:
        header: Authorization
        secret: s3cr3t
        expiration: 3600
    cors:
        mapping: /**
        allowedOrigins:
            - http://localhost:3000
        allowedMethods:
            - OPTIONS
            - GET
            - POST
            - PUT
            - DELETE
        allowCredentials: true
        maxAge: 3600
    roleHierarchy: "ROLE_ADMIN > ROLE_MANAGER ROLE_MANAGER > ROLE_EMPLOYEE ROLE_EMPLOYEE > ROLE_ANONYMOUS"
    realmName: "trackr development realm"

---
spring:
    profiles: production
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: validate
    datasource:
        initialize: false
        driverClassName: org.postgresql.Driver
        url: "${JDBC_DATABASE_URL}"
        maxActive: 10
        maxIdle: 5
        minIdle: 2
        initialSize: 5
        removeAbandoned: true
logging:
    config: classpath:logback-file.xml

---
spring:
    profiles: development
    jpa:
        show-sql: true
    datasource:
        initialize: true
auginc:
    jwt:
        expiration: 604800

---
spring:
    profiles: real-db
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: validate
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://127.0.0.1:5432/auginc
        username: postgres
        password: postgres
flyway:
    schemas: public

---
spring:
    profiles: in-memory-db
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:auginc;DB_CLOSE_DELAY\=-1
        username: sa
        password:
    jpa:
        hibernate:
            dialect: org.hibernate.dialect.H2Dialect
            ddl-auto: create
flyway:
    enabled: false
